# Generated by Django 6.1.1 on 2026-10-09 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='categorias.categorias')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.marca')),
                ('proveedores', models.ManyToManyField(related_name='productos_ofrecidos', to='proveedores.proveedor')),
            ],
        ),
    ]
