# Generated by Django 6.1.1 on 2026-10-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
    ]
